coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "test/**"
  - "hack/**"
  - "config/**"
  - "api/**/zz_generated*.go"
  - "cmd/**"

parsers:
  go:
    partials_as_hits: true
